### ISSUE TITLE
Client startup fails on Docker Mac due to dynamic module loading not available

### ISSUE THREAD

**Issue by scipilot** [virtualhere/docker#1]
I've tried running the client on Mac OS X Docker but it fails with an error that modprobe isnt' available and so it can't load usbip-core.ko.

I've tried both "Docker Desktop for Mac" 18.03.1-ce-mac65 and "Docker Machine" (with Virtual Box 6.0.5) which uses Boot2Docker's kernel.

Here is the run through with "Docker Desktop"

```
docker run -it --rm --privileged virtualhere/virtualhere-client:latest ash
Unable to find image 'virtualhere/virtualhere-client:latest' locally
latest: Pulling from virtualhere/virtualhere-client
6c40cc604d8e: Pull complete 
b9285ecbb6f3: Pull complete 
Digest: sha256:1d750a228fcd0d54b9e786b39c70b49af9ed29b5d15e9e681049ee94d8611289
Status: Downloaded newer image for virtualhere/virtualhere-client:latest
/ # ls
bin             lib             proc            srv             usr
dev             media           root            sys             var
etc             mnt             run             tmp             vhci-hcd.ko
home            opt             sbin            usbip-core.ko   vhclientx86_64
/ # uname -a
Linux a8e079429a51 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux
/ # ./vhclientx86_64 -n
VirtualHere Client: VirtualHere Client 4.6.7 starting (Compiled: Feb 23 2019 11:05:42)
/ # VirtualHere Client: Client OS is Linux 4.9.87-linuxkit-aufs x86_64
VirtualHere Client: Using config at /root/.vhui
VirtualHere Client: init_module error inserting 'usbip-core.ko': -1 Bad file descriptor. Your kernel probably was not compiled with dynamic module loading functionality
VirtualHere Client: 
^C
```

With Docker Machine / Boot2Docker it's the same, exctp the OS name is

      Linux acf8ee2e943f 4.14.104-boot2docker #1 SMP Thu Feb 28 20:58:57 UTC 2019 x86_64 Linux

So unless I'm missing something, I can't see how this image can work on those kernels,
(without doing hacky things like https://stackoverflow.com/a/37160346/209288).

I came to this container via your post here
https://virtualhere.com/content/virtual-here-client-docker
as I was having problems installing the client into a container of mine - with similar errors about modprobe missing.

thanks

**Comment by scipilot** [comment]
I realised while reading the Dockerfile that it actually builds the kernel modules agains the _current kernel_ - therefore I probably cannot `docker run` the prebuilt image hosted on Dockerhub because it was built against some unknown kernel. Well you probably know: did you build them on Docker Desktop for Mac (LinuxKit kernel)? Or on Docker Machine (boot2docker kernel)? Or hopefully not via DockerHub's own build server (unknown kernel)? 

Anyway the .ko files saved in the image root are probably not compatible with the shared kernel from boot2docker or LinuxKit bundled with the version of Docker _I have installed_.

BTW. I upgraded Docker to the last 18.x , which provides this version of boot2docker by default with Docker Machine:

    Linux d9b3b6706724 4.14.104-boot2docker #1 SMP Thu Feb 28 20:58:57 UTC 2019 x86_64 Linux

and this gives a slightly different error when trying to run the client (via docker run), which I feel supports the idea of it being an invalid module format rather than module loading not allowed at all. The "probably" in the error might be misleading.

```
VirtualHere Client: VirtualHere Client 4.6.7 starting (Compiled: Feb 23 2019 11:05:42)
VirtualHere Client: Client OS is Linux 4.14.104-boot2docker x86_64
VirtualHere Client: Using config at /root/.vhui
modprobe: can't change directory to '/lib/modules': No such file or directory
init_module error inserting 'usbip-core.ko': -1 Invalid module format. Your kernel probably was not compiled with dynamic module loading functionality
VirtualHere Client: init_module error inserting 'usbip-core.ko': -1 No error information. Your kernel probably was not compiled with dynamic module loading functionality
```


So I thought all I have to do is build the image locally from the Dockerfile (against the above boot2docker), but soon hit compiler problems.

    error: Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel
    make: *** [Makefile:1103: prepare-objtool] Error 1

So I added `libelf-dev`

this got further, but with warnings making the USBIP kernel config changes...

```
*** Default configuration is based on 'x86_64_defconfig'
#
# configuration written to .config
#
scripts/kconfig/conf  --oldconfig Kconfig
.config:4326:warning: override: reassigning to symbol USBIP_CORE
*
* Restart config...
```

and then errors:

```
 USB/IP support (USBIP_CORE) [M/n/y/?] m
    VHCI hcd (USBIP_VHCI_HCD) [M/n/?] m
      Number of ports per USB/IP virtual host controller (USBIP_VHCI_HC_PORTS) [8] 8
      Number of USB/IP virtual host controllers (USBIP_VHCI_NR_HCS) [1] 1
    Host driver (USBIP_HOST) [N/m/?] (NEW) 
Error in reading or end of file.

    Debug messages for USB/IP (USBIP_DEBUG) [N/y/?] (NEW) 
Error in reading or end of file.
```

then stopping at this which might be unrelated

```
#
# configuration written to .config
#
scripts/kconfig/conf  --silentoldconfig Kconfig
  SYSTBL  arch/x86/include/generated/asm/syscalls_32.h
...
  DESCEND  objtool
  HOSTCC   /srv/linux-4.14.104/tools/objtool/fixdep.o
  HOSTLD   /srv/linux-4.14.104/tools/objtool/fixdep-in.o
  LINK     /srv/linux-4.14.104/tools/objtool/fixdep
  CC       /srv/linux-4.14.104/tools/objtool/exec-cmd.o
In file included from /srv/linux-4.14.104/tools/include/linux/compiler.h:89,
                 from exec-cmd.c:2:
/srv/linux-4.14.104/tools/include/linux/types.h:10:10: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
mv: can't rename '/srv/linux-4.14.104/tools/objtool/.exec-cmd.o.tmp': No such file or directory
make[4]: *** [/srv/linux-4.14.104/tools/build/Makefile.build:97: /srv/linux-4.14.104/tools/objtool/exec-cmd.o] Error 1
make[3]: *** [Makefile:50: /srv/linux-4.14.104/tools/objtool/libsubcmd-in.o] Error 2
make[2]: *** [Makefile:54: /srv/linux-4.14.104/tools/objtool/libsubcmd.a] Error 2
make[1]: *** [Makefile:62: objtool] Error 2
make: *** [Makefile:1660: tools/objtool] Error 2
```

So I switched back to "Docker Desktop for Mac" / LinuxKit (I'd been using machine/boot2docker because it natively supports USB in experiments leading up to finding your product.) and tried building it against that.

This build succeeded.

However when starting the client, I still get an error that `/lib/modules` is not found:

```
/ # ./vhclientx86_64 
VirtualHere Client: VirtualHere Client 4.6.8 starting (Compiled: Mar 11 2019 12:11:33)
VirtualHere Client: Client OS is Linux 4.9.93-linuxkit-aufs x86_64
VirtualHere Client: Using config at /root/.vhui
modprobe: can't change directory to '/lib/modules': No such file or directory
VirtualHere Client: IPC available at /tmp/vhclient
```

So now it does start up, and I can use the client API, so I guess its working, but I can't seem to connect to the host running on Mac OSX natively. But that's probably another issue.

**Comment by scipilot** [comment]
I've got it working now.

So the short answer to anyone using this container is: you have to build the image locally.

    docker build -t virtualhere github.com/virtualhere/docker
    docker run -it --rm virtualhere ash

Which is the Docker equivalent of the last client FAQ answer about compiling for your kernel.

**Comment by eine** [comment]
@scipilot, besides building and running the container, did you get the virtualhere client to work inside it? I'm having issues on Docker Desktop for Windows. Both the client and the server seem to work properly and the device is shown by `lsusb`; but applications in the container are unable to use it (libusb/libusb#613).
