### ISSUE TITLE
Licensing when sharing a single device between a host and a container

### ISSUE THREAD

**Issue by eine** [virtualhere/docker#4]
Coming from libusb/libusb#613:

> [[@virtualhere](https://github.com/libusb/libusb/issues/613#issuecomment-522375329)]
> Use the device and then have a look in syslog, also you must use a
purchased virtualhere server.

Is the comment about using a purchased virtualhere server a strong suggestion or an actual requirement? Precisely, I am using:

- [VirtualHere Server for Windows 64-bit](https://www.virtualhere.com/sites/default/files/usbserver/vhusbdwin64.exe)
- [VirtualHere USB Console Client for Linux (amd64)](https://www.virtualhere.com/sites/default/files/usbclient/vhclientx86_64)

I am starting the server on a Windows 10 host, and running the client inside a docker container running on the same host. I am `USE`ing a single device with virtualhere, as explained in https://github.com/ghdl/docker/tree/feat-usbip/usbip#example-session

I'd like to spread the word about this useful tool, as an alternative to using an external 'bridge' SBC (such as a RPi) to program embedded devices (through USB) from docker containers running on a Windows 10 workstation. Since neither Hyper-V VMs nor Docker Desktop support sharing USB devices between the host and the containers, virtualhere is so handy. However, I'd like to clarify licensing requirements.

**Comment by virtualhere** [comment]
The console client does require a licensed server but at the moment i don't put a technical limitation in there to force that.

**Comment by eine** [comment]
I'm sorry, but I don't understand the terms yet.

> [Windows USB Server](https://www.virtualhere.com/windows_server_software)
> The trial edition **is restricted to sharing one device at a time**.

> [VirtualHere USB Server 4.0.0 License]
> You may:
> - **Install and use the Software on a Windows machine to share a single USB device (with no payment required) over a network. To share more than one USB device simultaneously from a single server you must purchase a License**.

> [Running the Client as a Background Service (Daemon)](https://www.virtualhere.com/client_service)
>  When the VirtualHere USB Client is installed as a background service it will automatically start up when the operating system boots, and will automatically connect to any devices you have specified.. The message log can be viewed in the Event Viewer (under Windows), Console Viewer (under OSX), or tail /var/log/syslog (under Linux).
>
> **THE VIRTUALHERE USB SERVER MUST BE PURCHASED TO USE THIS FEATURE**

> [Linux Console Client](https://www.virtualhere.com/linux_console)
> Running the Linux Client in the console is usually a two step process.
>
> Step 1. Start the Client as a daemon so that it runs in the background using the -n flag. You can move it into an init.d script so it runs on startup as a daemon
> Step 2. Run the client again and this time use the -t argument to control the daemon
> 
> Note: **when running the client as a daemon (step 1) the VirtualHere Server it connects to must be purchased**

I interpret that, having downloaded and executed VirtualHere USB Server 4.0.0 on Windows 10, I have effectively purchased it; but no payment is required for a single USB device. Therefore, using the Linux Console Client is allowed. Moreover, I am not starting the client as a background service (daemon); i.e. I'm not using `-n`. Hence, it seems that the comments in the third and fourth quotes do not apply. Should this not be relevant, I suggest updating the docs, so it is clear that the Linux Console Client cannot be used without paying for a server license.

By the same token, does this licensing limitation apply to GUI clients too? I found no limitation in the license of `vhui64.exe`. Therefore, assume that VirtualHere USB Server 4.0.0 for Windows can be used with any number of clients for Windows, as long as a single device is shared at a time. Is it the same for 'Linux GUI' (`vhuit64`)?

**Comment by virtualhere** [comment]
Yes with the console client you need to purchase. The word "purchase" means what he has for millennia which is an exchange of money :)  

However there is a bug which allows it to run as a console without purchase in Linux, that i havent fixed yet. I need to do this as i have large companies using virtualhere , wanting support, as well as chinese manufacturers trying to steal the software on a monthly basis, so its not really viable. When the GUI can be hidden it invites theft.

So  Ive blocked the windows client and osx client running as a service for many years, and i will block the linux console from running if the license is not purchased. Then there wont be any confusion.

I wrote virtualhere over many years because there was no good usbip product out there, and now docker,cloud computing,game streaming etc has come along and its popular functionality to have.

**Comment by eine** [comment]
> Yes with the console client you need to purchase. The word "purchase" means what he has for millennia which is an exchange of money :)

I got lost in the translation here :S. I thought it meant 'request'/'ask for a service' rather than 'pay'.

> However there is a bug which allows it to run as a console without purchase in Linux, that i havent fixed yet. I need to do this as i have large companies using virtualhere , wanting support, as well as chinese manufacturers trying to steal the software on a monthly basis, so its not really viable.

I understand it. However, I do not need the tool/service ATM, so I'm willing to respect your licensing approach, even though it can be easily avoided technically. I.e., I'm ok with not using it, if mine is not an expected use case.

> So Ive blocked the windows client and osx client running as a service for many years, and i will block the linux console from running if the license is not purchased. Then there wont be any confusion.

I appreciate the clarification.

> I wrote virtualhere over many years because there was no good usbip product out there, and now docker,cloud computing,game streaming etc has come along and its popular functionality to have.

I understand that, and I think that the product has multiple interesting features, specially for users/companies that need remote access, multi-platform support and ease of configuration for multiple devices. Nevertheless, my use case is quite particular:

I'm trying to fill the gap that allows to program FPGA boards from docker containers on Win10, with designs synthesised using open source CLI tools. Using a container is an alternative to 'fighting' with libftdi/libusb/libusbK/WinUSB/Zadig on Windows 10. These tools support very few boards and all of them are for hobbyist with prices between USD25-60. Therefore, the solution needs to be:

- Easier to set up than Zadig, VirtualBox or a Single Board Computer (SBC).
- 'Cheaper' than installing VirtualBox or using a SBC and not more expensive than the development board with FPGA.
- Open source.

From this point of view, using virtualhere is a somehow valid workaround only if it is free and only because it fills a very specific gap (USB/IP driver-to-server logic on Windows). It is slightly easier to set up than other alternatives, and it is 'cheaper' than VirtualBox in regard to disk/memory/cpu usage. However, since the license costs USD49, the target audience would rather buy two RPis and either use Zadig or the commercial (free) software from the vendor. Most of the cool features of virtualhere (userspace linux server, linux client, SSL, Bonjour...) are not useful in this context because the client and the server are running on the same machine (it is a local port). The really relevant feature of virtualhere here is that you managed to use VBoxUSB instead of implementing your own driver for Windows. I don't know how much of the complexity is to be acknowledged to VirtualBox and how much to you, but I must say that it works really well.

> When the GUI can be hidden it invites theft.

If I don't get it wrong, you are OK with the Linux GUI client being used with the free Windows server, isn't it? I.e., you don't mind users sharing a single device between any client and any server, as long as they are 'forced' to know that the product they are using is virtualhere (and not some rebranded copy).

**Comment by virtualhere** [comment]
Yes thats fine, if the GUI is shown thats ok to use the free server, it tempts users to purchase.

VirtualHere is not open source software and it costs money, so it wont fulfill your requirements, buts thats ok I dont have to please everyone :)

**Comment by eine** [comment]
> Yes thats fine, if the GUI is shown thats ok to use the free server, it tempts users to purchase.

Thanks for stating it explicitly.

> VirtualHere is not open source software and it costs money, so it wont fulfill your requirements, buts thats ok I dont have to please everyone :)

That's what I wanted to explain. Still, it is a non-open alternative which is based on many open source projects (more than we know about vendor tools), and it is cheap enough as long as free server and clients can be used. If tempting the users to purchase it is good feedback for you, we are all happy :). I will personally consider purchasing it for other more complex setups.
